### PR TITLE
SVG version of the logo

### PR DESCRIPTION
**Pull request by gilbarbara**
Fixes https://github.com/tastejs/tastejs.github.com/issues/4.

### CODE REVIEW

**Comment by sindresorhus** [comment]
So the shine on the head is actually the same, but the head itself is darker in the SVG version which makes the shine stand out more. Can you turn the opacity down a little bit?

Otherwise, it's perfect! :)

**Comment by gilbarbara** [comment]
You mean this?
shine

I lowered the opacity from 30% to 20% now.

**Comment by sindresorhus** [comment]
Yup. Looks good :)

**Comment by gilbarbara** [comment]
Ahh, ok. The salmon color comes from the gradient for the base path (the whole body).
I'll try to add another step in this gradient and see if doesn't change other color interactions too much.

**Comment by gilbarbara** [comment]
@sindresorhus Hey!
So I did a rework from ground up. Let me know if this version is better..

[s]

**Comment by sindresorhus** [comment]
@gilbarbara Oh yes! Looks superb :)

**Comment by sindresorhus** [comment]
Thanks again for working on this. Would love to read a blog post about your process. Hint hint ;)

**Comment by gilbarbara** [comment]
@sindresorhus Yay! I'm glad you liked it!
I'll definitely write about the whole SVG saga..

Cheers

**Pull request closed without merging**
